server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: alg_vis
  datasource:
    url: jdbc:mysql://localhost:3306/alg_vis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jianning.alg_vis.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true